{% set name = "convert3d" %}
{% set version = "1.4.2" %}
{% set ref = "2abc64bfa8385941359ec6a5a34e77b0d0f4e8b1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/pyushkevich/c3d/archive/{{ ref }}.tar.gz
  sha256: 54d060e68b28845654de4db346f9ef05c5f9e92a7124d6bdb78deb140b1cc099

build:
  number: 1
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - cmake
    - ninja
  host:
    - libitk-devel
  run:
    - fftw
    - {{ pin_compatible('libitk', min_pin='x.x', max_pin='x.x') }}

test:
  commands:
    - c3d -version

about:
  home: https://www.itksnap.org/c3d
  license: GPL-3.0-or-later
  license_file: COPYING.txt
  summary: 'ITK-based image manipulation tool'
  description: |
    Convert3d is a command-line tool for converting 3D (or 4D) images between
    common file formats. The tool also includes a growing list of commands for
    image manipulation, such as thresholding and resampling. The tool can also
    be used to obtain information about image files.
  doc_url: https://sourceforge.net/p/c3d/git/ci/master/tree/doc/c3d.md
  dev_url: https://github.com/pyushkevich/c3d

extra:
  recipe-maintainers:
    - ghisvail
    - pyushkevich
