{% set name = "convert3d" %}
{% set version = "1.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: https://github.com/pyushkevich/c3d.git
  git_rev: "7ecbb99"

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - ninja
  host:
    - libitk-devel
  run:
    - fftw
    - libitk

test:
  commands:
    - c3d -version

about:
  home: https://www.itksnap.org/c3d
  license: GPL-3.0-or-later
  license_file: COPYING.txt
  summary: 'ITK-based image manipulation tool'
  description: |
    Convert3d is a command-line tool for converting 3D (or 4D) images between
    common file formats. The tool also includes a growing list of commands for
    image manipulation, such as thresholding and resampling. The tool can also
    be used to obtain information about image files.
  doc_url: https://sourceforge.net/p/c3d/git/ci/master/tree/doc/c3d.md
  dev_url: https://github.com/pyushkevich/c3d

extra:
  recipe-maintainers:
    - ghisvail
    - pyushkevich
